// The renderer ↔ main contract. Record data types come from the Rust engine
// (`ts-rs` output in `./generated/`, regenerated by `just gen-types` in
// `esm/`, never hand-edited): `Op` is every operation the engine runs and
// `OpOutput` maps each op's tag to its result type, so `Fo76Api.run` is typed
// end to end with no per-op code here. The rest of this file is what is not a
// Rust type: channel names, open-database handles, and the API surface itself.

import type { DiffOptions } from './generated/DiffOptions'
import type { DiffResult } from './generated/DiffResult'
import type { FileInfo } from './generated/FileInfo'
import type { Op } from './generated/Op'
import type { OpOutput } from './generated/OpOutput'
import type { RecordSel } from './generated/RecordSel'

export type { CoverageReport } from './generated/CoverageReport'
export type { DiffOptions } from './generated/DiffOptions'
export type { DiffResult } from './generated/DiffResult'
export type { FileInfo } from './generated/FileInfo'
export type { FilterOp } from './generated/FilterOp'
export type { FilterResult } from './generated/FilterResult'
export type { GroupChild } from './generated/GroupChild'
export type { GroupLabel } from './generated/GroupLabel'
export type { GroupNode } from './generated/GroupNode'
export type { Markers } from './generated/Markers'
export type { Op } from './generated/Op'
export type { OpOutput } from './generated/OpOutput'
export type { RawRecordView } from './generated/RawRecordView'
export type { RawSubrecordView } from './generated/RawSubrecordView'
/** One record present in both snapshots whose decoded fields differ. */
export type { RecordDiff as RecordChangeDiff } from './generated/RecordDiff'
export type { RecordResult } from './generated/RecordResult'
export type { RecordRow } from './generated/RecordRow'
export type { RecordSel } from './generated/RecordSel'
/** Lightweight record identity for added/removed diff entries (renamed to
 * avoid colliding with the tree module's own record stub). */
export type { RecordStub as RecordStubDiff } from './generated/RecordStub'
/** Full envelope returned by a recursive refs walk. */
export type { RefList as RefListResult } from './generated/RefList'
export type { RefPathNode } from './generated/RefPathNode'
export type { RefRow } from './generated/RefRow'
export type { ResolveDepth } from './generated/ResolveDepth'

/** Every op that runs against one open database (`diff` needs two). */
export type RunnableOp = Exclude<Op, { op: 'diff' }>

/** The result type of running `T`. */
export type OpResult<T extends Op> = OpOutput[T['op']]

/** Electron IPC channel names. */
export const CH = {
  openFileDialog: 'open-file-dialog',
  openFolderDialog: 'open-folder-dialog',
  openDatabase: 'open-database',
  closeDatabase: 'close-database',
  listOpen: 'list-open',
  parseFormId: 'parse-form-id',
  run: 'run-op',
  diff: 'diff',
} as const

export type DbId = string

export interface DbHandle {
  id: DbId
  path: string
  info: FileInfo
}

/** What a diff of two open databases asks for: an optional record-type
 * filter and any `DiffOptions` fields to override (the rest default). */
export interface DiffRequest {
  record_type: string | null
  options: Partial<DiffOptions>
}

export interface Fo76Api {
  openFileDialog(): Promise<string | null>
  openFolderDialog(): Promise<string | null>
  openDatabase(path: string): Promise<DbHandle>
  closeDatabase(id: DbId): Promise<void>
  listOpen(): Promise<DbHandle[]>
  parseFormId(s: string): Promise<string>
  /** Run one engine op against an open database. */
  run<T extends RunnableOp>(id: DbId, op: T): Promise<OpResult<T>>
  diff(oldId: DbId, newId: DbId, request: DiffRequest): Promise<DiffResult>
}

/** A selector for a FormID or EditorID typed by the user or taken from a
 * decoded record: FormID first, then EditorID. */
export function sel(token: string): RecordSel {
  return { kind: 'auto', value: token }
}
