#!/usr/bin/env python3
"""
regen_wire_constants.py — regenerate the checked-in `tools/wire_constants.py`
from the Rust source of truth, via `esm dump-wire-constants` (see
`cmd_dump_wire_constants` in `src/bin/cli.rs`).

`esm_gateway.py`'s module docstring names five Rust source files it mirrors
"exactly": daemon-discovery timeout constants (`backend.rs`), the `Op`
discriminant strings and `RefList` walk-depth default (`ipc.rs`), the
`FormId` display format (`formid.rs`), and every `esm --local diff` flag
name (`cli.rs`'s `DiffArgs`). This script + the checked-in
`wire_constants.py` it writes are the drift protection for those facts,
mirroring the shape of
`tools/extractor/hardcoded.py` (regenerate a checked-in artifact from the
built `esm` binary, then `git diff --exit-code` it in CI -- see
`.github/workflows/ci.yml`'s "regen wire_constants.py drift guard" step in
the `audit` job) and `just gen-types` (same shape for the N-API TypeScript
DTOs). `src/bin/cli/wire_constants.rs`'s own `tests` module is the earlier
half of the same guard: it reads the checked-in file and fails under plain
`cargo test` when it no longer matches what the Rust side emits, so drift
surfaces before a push rather than only in CI.

Usage:
    cargo build --release          # from esm/ -- builds the dump source
    python3 tools/regen_wire_constants.py [--esm-bin PATH]

    # CI drift guard (also runnable locally):
    python3 tools/regen_wire_constants.py
    git diff --exit-code tools/wire_constants.py

Python 3, stdlib only.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import esm_gateway  # noqa: E402

OUT = SCRIPT_DIR / "wire_constants.py"

HEADER = '''\
#!/usr/bin/env python3
"""
wire_constants.py -- # GENERATED by tools/regen_wire_constants.py from
`esm dump-wire-constants` (see `cmd_dump_wire_constants` in
src/bin/cli.rs). DO NOT EDIT BY HAND -- re-run the regen script instead;
CI fails if this file drifts from what the Rust source currently emits
(the "regen wire_constants.py drift guard" step in .github/workflows/ci.yml's
`audit` job).

This is the checked-in half of esm_gateway.py's wire-format mirror: the
daemon-discovery timeout constants (backend.rs), the `Op` discriminant
strings and reverse-reference walk-depth default (ipc.rs), the `FormId`
display format (formid.rs), and every `esm --local diff` flag name
(cli.rs's `DiffArgs`). `esm_gateway.py` imports from here instead of
hardcoding these facts inline.

Python 3, stdlib only.
"""

from __future__ import annotations
'''


def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


def render(data: dict) -> str:
    lines = [HEADER]
    lines.append(f"DAEMON_FILENAME: str = {data['daemon_filename']!r}")
    lines.append(f"CONNECT_TIMEOUT_SECS: float = {data['connect_timeout_secs']!r}")
    lines.append(f"HEALTH_POLL_INTERVAL_SECS: float = {data['health_poll_interval_secs']!r}")
    lines.append(f"HEALTH_POLL_MAX_SECS: float = {data['health_poll_max_secs']!r}")
    lines.append(f"OP_TIMEOUT_SECS: float = {data['op_timeout_secs']!r}")
    lines.append(f"DEFAULT_MAX_DEPTH: int = {data['default_max_depth']!r}")
    lines.append("")
    lines.append("#: Every Op::* variant's wire discriminant (ipc.rs's")
    lines.append('#: `#[serde(tag = "op", rename_all = "snake_case")]`).')
    op_names = ",\n    ".join(repr(name) for name in data["op_names"])
    lines.append(f"OP_NAMES: frozenset[str] = frozenset({{\n    {op_names},\n}})")
    lines.append("")
    lines.append("#: raw u32 (decimal str) -> FormId::display()'s \"0x{:08X}\" output,")
    lines.append("#: for asserting Python's own hex formatting against real Rust output.")
    examples = ",\n    ".join(
        f"{k!r}: {v!r}" for k, v in data["form_id_display_examples"].items()
    )
    lines.append(f"FORM_ID_DISPLAY_EXAMPLES: dict[str, str] = {{\n    {examples},\n}}")
    lines.append("")
    lines.append("#: Every long-form flag `esm --local diff` accepts (DiffArgs, cli.rs).")
    diff_flags = ",\n    ".join(repr(flag) for flag in data["diff_flags"])
    lines.append(f"DIFF_FLAGS: frozenset[str] = frozenset({{\n    {diff_flags},\n}})")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    import argparse

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--esm-bin", help="Path to the esm CLI binary (default: workspace release build, else $PATH).")
    args = ap.parse_args(argv)

    try:
        esm_bin = esm_gateway.find_esm_binary(args.esm_bin)
    except esm_gateway.DaemonError as exc:
        eprint(f"error: {exc}")
        return 1

    result = subprocess.run(
        [str(esm_bin), "dump-wire-constants"],
        capture_output=True,
        text=True,
        stdin=subprocess.DEVNULL,
    )
    if result.returncode != 0:
        eprint(f"error: {esm_bin} dump-wire-constants failed: {result.stderr.strip()}")
        return 1
    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        eprint(f"error: unparseable JSON from {esm_bin} dump-wire-constants: {exc}")
        return 1

    OUT.write_text(render(data), encoding="utf-8")
    eprint(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
