#!/usr/bin/env python3
"""
wire_constants.py -- # GENERATED by tools/regen_wire_constants.py from
`esm dump-wire-constants` (see `cmd_dump_wire_constants` in
src/bin/cli.rs). DO NOT EDIT BY HAND -- re-run the regen script instead;
CI fails if this file drifts from what the Rust source currently emits
(the "regen wire_constants.py drift guard" step in .github/workflows/ci.yml's
`audit` job).

This is the checked-in half of esm_gateway.py's wire-format mirror: the
daemon-discovery timeout constants (backend.rs), the `Op` discriminant
strings and reverse-reference walk-depth default (ipc.rs), the `FormId`
display format (formid.rs), and every `esm --local diff` flag name
(cli.rs's `DiffArgs`). `esm_gateway.py` imports from here instead of
hardcoding these facts inline.

Python 3, stdlib only.
"""

from __future__ import annotations

DAEMON_FILENAME: str = 'esm-daemon.json'
CONNECT_TIMEOUT_SECS: float = 2.0
HEALTH_POLL_INTERVAL_SECS: float = 0.1
HEALTH_POLL_MAX_SECS: float = 30.0
OP_TIMEOUT_SECS: float = 300.0
DEFAULT_MAX_DEPTH: int = 8

#: Every Op::* variant's wire discriminant (ipc.rs's
#: `#[serde(tag = "op", rename_all = "snake_case")]`).
OP_NAMES: frozenset[str] = frozenset({
    'file_info',
    'record',
    'record_bulk',
    'record_raw',
    'list_by_type',
    'list_type_records',
    'filter_type_records',
    'list_type_field_paths',
    'search',
    'referenced_by',
    'ref_path',
    'walk',
    'chase',
    'drop_table',
    'list_groups',
    'list_type_children',
    'list_group_children',
    'record_stub_at',
    'coverage',
    'diff',
    'shutdown',
})

#: raw u32 (decimal str) -> FormId::display()'s "0x{:08X}" output,
#: for asserting Python's own hex formatting against real Rust output.
FORM_ID_DISPLAY_EXAMPLES: dict[str, str] = {
    '0': '0x00000000',
    '17983': '0x0000463F',
    '11259375': '0x00ABCDEF',
    '4294967295': '0xFFFFFFFF',
}

#: Every long-form flag `esm --local diff` accepts (DiffArgs, cli.rs).
DIFF_FLAGS: frozenset[str] = frozenset({
    '--bodies',
    '--curves-dir',
    '--curves-dir-a',
    '--curves-dir-b',
    '--exclude-type',
    '--json',
    '--keep-noise',
    '--lang',
    '--localization-ba2',
    '--localization-ba2-a',
    '--localization-ba2-b',
    '--pretty',
    '--startup-ba2',
    '--startup-ba2-a',
    '--startup-ba2-b',
    '--strings-dir',
    '--strings-dir-a',
    '--strings-dir-b',
    '--type',
})
