//! Hand-written companions to the `ts-rs`-derived exports (see the various
//! `#[cfg_attr(test, derive(ts_rs::TS))]` types across `src/`). These two
//! generators don't mirror a single Rust struct — one flattens the embedded
//! schema's record-name table, the other mirrors the decode-coverage marker
//! key constants (`esm::decode::markers`) — so they're written by hand here
//! rather than derived.
//!
//! Both are named `export_bindings_*` so `just gen-types` (`cargo test
//! export_bindings`) picks them up alongside every `ts-rs`-generated test.
//! Output directory matches the `ts-rs` exports: `TS_RS_EXPORT_DIR` when set
//! (the `gen-types` recipe sets it), else `../esm-viewer/src/shared/generated`
//! relative to this crate's root — the same effective default `ts-rs` itself
//! would resolve to if `TS_RS_EXPORT_DIR` were pointed there.

use esm::schema::Schema;
use std::path::PathBuf;

/// Resolve the shared output directory for all generated TypeScript mirrors.
/// Mirrors `ts-rs`'s own `TS_RS_EXPORT_DIR` env var so one variable controls
/// every generator (`ts-rs`-derived types and these two hand-written ones).
fn export_dir() -> PathBuf {
    match std::env::var("TS_RS_EXPORT_DIR") {
        Ok(dir) => PathBuf::from(dir),
        Err(_) => PathBuf::from("../esm-viewer/src/shared/generated"),
    }
}

/// A JS/TS double-quoted string literal for `s`, using `serde_json` for
/// correct escaping (schema record names/EditorID-derived signatures are
/// plain ASCII in practice, but this is defensive against stray quotes).
fn ts_string_literal(s: &str) -> String {
    serde_json::to_string(s).expect("string always serializes")
}

/// Generate `recordTypeNames.generated.ts`: signature -> display name, sourced
/// from the embedded schema's `records[sig].name` (the same data
/// `esm-viewer/src/renderer/src/recordTypeNames.ts` used to hand-copy).
#[test]
fn export_bindings_record_type_names() {
    let schema = Schema::load_embedded().expect("load embedded schema");

    let mut entries: Vec<(&str, &str)> = schema
        .records
        .iter()
        .map(|(sig, def)| (sig.as_str(), def.name.as_str()))
        .collect();
    entries.sort_by_key(|(sig, _)| *sig);

    let mut out = String::new();
    out.push_str(
        "// @generated by `esm/tests/gen_bindings.rs` (`just gen-types`). Do not hand-edit.\n",
    );
    out.push_str("/** Human-friendly record type names, sourced from `esm/schema/fo76.json`'s\n");
    out.push_str(" * `records[sig].name`. */\n");
    out.push_str("export const RECORD_TYPE_NAMES: Record<string, string> = {\n");
    for (sig, name) in entries {
        out.push_str(&format!(
            "  {}: {},\n",
            ts_string_literal(sig),
            ts_string_literal(name)
        ));
    }
    out.push_str("}\n");

    let dir = export_dir();
    std::fs::create_dir_all(&dir).expect("create export dir");
    std::fs::write(dir.join("recordTypeNames.generated.ts"), out).expect("write generated file");
}

/// Generate `markers.generated.ts`: the four schema decode-coverage marker
/// keys, sourced from `esm::decode::markers` (the single source of truth the
/// decoder itself inserts these under). Keeps
/// `esm-viewer/src/renderer/src/lib/alignedTree.ts`'s `coverageBadges()` from
/// hardcoding these strings independently of the decoder that produces them.
#[test]
fn export_bindings_markers() {
    use esm::decode::markers;

    let mut out = String::new();
    out.push_str(
        "// @generated by `esm/tests/gen_bindings.rs` (`just gen-types`). Do not hand-edit.\n",
    );
    out.push_str("/** Schema decode-coverage marker keys — mirrors `esm::decode::markers` (the\n");
    out.push_str(
        " * single source of truth the decoder inserts these under). See \"Decode output\n",
    );
    out.push_str(" * key conventions\" in esm/CLAUDE.md. */\n");
    out.push_str("export const MARKERS = {\n");
    out.push_str(&format!(
        "  UNKNOWN_RECORD: {},\n",
        ts_string_literal(markers::UNKNOWN_RECORD)
    ));
    out.push_str(&format!("  RAW: {},\n", ts_string_literal(markers::RAW)));
    out.push_str(&format!(
        "  UNMAPPED: {},\n",
        ts_string_literal(markers::UNMAPPED)
    ));
    out.push_str(&format!(
        "  UNRESOLVED: {},\n",
        ts_string_literal(markers::UNRESOLVED)
    ));
    out.push_str("} as const\n");

    let dir = export_dir();
    std::fs::create_dir_all(&dir).expect("create export dir");
    std::fs::write(dir.join("markers.generated.ts"), out).expect("write generated file");
}
