/** Human-friendly record type names, sourced from `esm/schema/fo76.json`'s
 * `records[sig].name`. Generated by `esm/tests/gen_bindings.rs` (`just
 * gen-types` in `esm/`) — see `../../shared/generated/recordTypeNames.generated.ts`.
 * Do NOT hand-edit the generated file; this thin wrapper just adds the
 * `formatRecordType` helper on top. */
export { RECORD_TYPE_NAMES } from '../../shared/generated/recordTypeNames.generated'
import { RECORD_TYPE_NAMES } from '../../shared/generated/recordTypeNames.generated'

/** "SIG - Name" if a human name is known for `sig`, else the bare `sig`. */
export function formatRecordType(sig: string): string {
  const name = RECORD_TYPE_NAMES[sig]
  return name ? `${sig} - ${name}` : sig
}
