/** Human-friendly record type names, sourced from `esm/schema/fo76.json`'s
 * `records[sig].name`. Hand-mirrored (not generated at build time) — same
 * convention as `shared/api-types.ts` mirroring the Rust N-API surface. */
export const RECORD_TYPE_NAMES: Record<string, string> = {
  "AACT": "Action",
  "AAMD": "Aim Assist Model Data",
  "AAPD": "Aim Assist Pose Data",
  "ACHR": "Placed NPC",
  "ACTI": "Activator",
  "ADDN": "Addon Node",
  "AECH": "Audio Effect Chain",
  "ALCH": "Ingestible",
  "AMDL": "Aim Model",
  "AMMO": "Ammunition",
  "ANIO": "Animated Object",
  "AORU": "Attraction Rule",
  "ARMA": "Armor Addon",
  "ARMO": "Armor",
  "ARTO": "Art Object",
  "ASPC": "Acoustic Space",
  "ASTM": "Unknown - ASTM",
  "ASTP": "Association Type",
  "ATXO": "ATX Default Object",
  "AUVF": "AUVF - Unknown",
  "AVIF": "Actor Value Information",
  "AVTR": "Avatar",
  "BNDS": "Bendable Spline",
  "BOOK": "Book",
  "BPTD": "Body Part Data",
  "CAMS": "Camera Shot",
  "CELL": "Cell",
  "CHAL": "Challenge",
  "CLAS": "Class",
  "CLFM": "Color",
  "CLMT": "Climate",
  "CMPO": "Component",
  "CMPT": "Camp Title",
  "CNCY": "Currency",
  "CNDF": "Condition Form",
  "COBJ": "Constructible Object",
  "COEN": "Consumable Entitlement",
  "COLL": "Collision Layer",
  "CONT": "Container",
  "CPRD": "Challenge Pass Reward Data",
  "CPTH": "Camera Path",
  "CSEN": "Crate Service Entitlement",
  "CSTY": "Combat Style",
  "CURV": "Curve Table",
  "DCGF": "Daily Content Group",
  "DEBR": "Debris",
  "DFOB": "Default Object",
  "DIAL": "Dialog Topic",
  "DIST": "District",
  "DLBR": "Dialog Branch",
  "DLVW": "Dialog View",
  "DMGT": "Damage Type Resist",
  "DOBJ": "Default Object Manager",
  "DOOR": "Door",
  "ECAT": "Emote Category",
  "EFSH": "Effect Shader",
  "EMOT": "Emote",
  "ENCH": "Enchantment",
  "ENTM": "Entitlement",
  "EQUP": "Equip Type",
  "EXPL": "Explosion",
  "FACT": "Faction",
  "FISH": "Fish",
  "FLOR": "Flora",
  "FLST": "FormID List",
  "FSTP": "Footstep",
  "FSTS": "Footstep Set",
  "FURN": "Furniture",
  "GCVR": "Ground Cover",
  "GDRY": "God Rays",
  "GLOB": "Global",
  "GMRW": "Gameplay Reward",
  "GMST": "Game Setting",
  "GRAS": "Grass",
  "HAZD": "Hazard",
  "HDPT": "Head Part",
  "IDLE": "Idle Animation",
  "IDLM": "Idle Marker",
  "IMAD": "Image Space Adapter",
  "IMGS": "Image Space",
  "INFO": "Dialog response",
  "INGR": "Ingredient",
  "INNR": "Instance Naming Rules",
  "IPCT": "Impact",
  "IPDS": "Impact Data Set",
  "KEYM": "Key",
  "KSSM": "Sound Keyword Mapping",
  "KYWD": "Keyword",
  "LAYR": "Layer",
  "LCRT": "Location Reference Type",
  "LCTN": "Location",
  "LENS": "Lens Flare",
  "LGDI": "Legendary Item",
  "LGTM": "Lighting Template",
  "LIGH": "Light",
  "LOUT": "Loadout",
  "LSCR": "Load Screen",
  "LTEX": "Landscape Texture",
  "LVLI": "Leveled Item",
  "LVLN": "Leveled NPC",
  "LVLP": "Leveled Pack In",
  "LVPC": "Leveled Perk Card",
  "MATO": "Material Object",
  "MATT": "Material Type",
  "MDSP": "Model Swap",
  "MESG": "Message",
  "MGEF": "Magic Effect",
  "MISC": "Misc. Item",
  "MOVT": "Movement Type",
  "MSTT": "Moveable Static",
  "MSWP": "Material Swap",
  "MUSC": "Music Type",
  "MUST": "Music Track",
  "NAVI": "Navmesh Info Map",
  "NAVM": "Navmesh",
  "NOCM": "Navmesh Obstacle Manager",
  "NOTE": "Note",
  "NPC_": "Non-Player Character",
  "OMOD": "Object Modification",
  "OTFT": "Outfit",
  "OVIS": "Object Visibility Manager",
  "PACH": "Power Armor Chassis",
  "PACK": "Package",
  "PCRD": "Perk Card",
  "PEPF": "Event Playlist",
  "PERK": "Perk",
  "PGRE": "Placed Projectile",
  "PHZD": "Placed Hazard",
  "PKIN": "Pack-In",
  "PLYR": "Player Reference",
  "PLYT": "Player Title",
  "PMFT": "Photo Mode Feature",
  "PMIS": "Placed Missile",
  "PPAK": "Perk Card Pack",
  "PROJ": "Projectile",
  "QMDL": "Quest Module",
  "QUST": "Quest",
  "RACE": "Race",
  "REFR": "Placed Object",
  "REGN": "Region",
  "RELA": "Relationship",
  "RESO": "Resource",
  "REVB": "Reverb Parameters",
  "RFCT": "Visual Effect",
  "RFGP": "Reference Group",
  "SCCO": "Scene Collection",
  "SCEN": "Scene",
  "SCOL": "Static Collection",
  "SCSN": "Sound Category Snapshot",
  "SECH": "Sound Echo Marker",
  "SMBN": "Story Manager Branch Node",
  "SMEN": "Story Manager Event Node",
  "SMQN": "Story Manager Quest Node",
  "SNCT": "Sound Category",
  "SNDR": "Sound Descriptor",
  "SOPM": "Sound Output Model",
  "SOUN": "Sound Marker",
  "SPEL": "Spell",
  "SPGD": "Shader Particle Geometry",
  "STAG": "Animation Sound Tag Set",
  "STAT": "Static",
  "STHD": "Spell Threshold Data",
  "STMP": "Snap Template",
  "STND": "Snap Template Node",
  "TACT": "Talking Activator",
  "TEPF": "Infestation Event Playlist",
  "TERM": "Terminal",
  "TRAP": "Trap",
  "TREE": "Tree",
  "TRNS": "Transform",
  "TXST": "Texture Set",
  "UTIL": "Utility",
  "VOLI": "Volumetric Lighting",
  "VTYP": "Voice Type",
  "WATR": "Water",
  "WAVE": "Wave Encounter",
  "WEAP": "Weapon",
  "WRLD": "Worldspace",
  "WSPR": "Workshop Permissions",
  "WTHR": "Weather",
  "ZOOM": "Zoom",
}

/** "SIG - Name" if a human name is known for `sig`, else the bare `sig`. */
export function formatRecordType(sig: string): string {
  const name = RECORD_TYPE_NAMES[sig]
  return name ? `${sig} - ${name}` : sig
}
