//! CTDA (Condition Data) subrecord decoder.
//!
//! Decodes the 32-byte CTDA struct: extracts the comparison operator from the
//! type byte, resolves the function index to a human-readable name, and decodes
//! each parameter field according to the function's declared parameter types.

use crate::decode::{hex, resolve_formid, DecodeContext};
use crate::formid::FormId;
use serde_json::{json, Map, Value};

// Comparison operators encoded in bits 5-7 of the CTDA type byte.
const OPERATORS: [&str; 6] = [
    "Equal To",
    "Not Equal To",
    "Greater Than",
    "Greater Than Or Equal To",
    "Less Than",
    "Less Than Or Equal To",
];

const RUN_ON: [&str; 17] = [
    "Subject", "Target", "Reference", "Combat Target", "Linked Reference",
    "Quest Alias", "Package Data", "Event Data", "Unknown 8", "Command Target",
    "Event Camera Ref", "My Killer", "Active Players", "Potential Players",
    "Player Teammates", "Target List", "Instance Owner",
];

// Parameter classification:
//   'N' = None (no param / skip)
//   'F' = Float (f32)
//   'I' = Integer (i32)
//   'S' = String (comes from CIS1/CIS2, not the 4-byte field)
//   'A' = ActorValue (u32; not yet named)
//   'R' = FormID reference
//
// Table is sorted by function index for binary search.
const FUNCTIONS: &[(u32, &str, char, char, char)] = &[
    (0_u32, "GetWantBlocking", 'N', 'N', 'N'),
    (1_u32, "GetDistance", 'R', 'N', 'N'),
    (2_u32, "AddItem", 'N', 'N', 'N'),
    (3_u32, "SetEssential", 'N', 'N', 'N'),
    (5_u32, "GetLocked", 'N', 'N', 'N'),
    (6_u32, "GetPos", 'I', 'N', 'N'),
    (8_u32, "GetAngle", 'I', 'N', 'N'),
    (10_u32, "GetStartingPos", 'I', 'N', 'N'),
    (11_u32, "GetStartingAngle", 'I', 'N', 'N'),
    (12_u32, "GetSecondsPassed", 'N', 'N', 'N'),
    (14_u32, "GetValue", 'A', 'N', 'N'),
    (18_u32, "GetCurrentTime", 'N', 'N', 'N'),
    (24_u32, "GetScale", 'N', 'N', 'N'),
    (25_u32, "IsMoving", 'N', 'N', 'N'),
    (26_u32, "IsTurning", 'N', 'N', 'N'),
    (27_u32, "GetLineOfSight", 'R', 'N', 'N'),
    (32_u32, "GetInSameCell", 'R', 'N', 'N'),
    (35_u32, "GetDisabled", 'N', 'N', 'N'),
    (36_u32, "MenuPaused", 'N', 'N', 'N'),
    (39_u32, "GetDisease", 'N', 'N', 'N'),
    (41_u32, "GetClothingValue", 'N', 'N', 'N'),
    (42_u32, "SameFaction", 'R', 'N', 'N'),
    (43_u32, "SameRace", 'R', 'N', 'N'),
    (44_u32, "SameSex", 'R', 'N', 'N'),
    (45_u32, "GetDetected", 'R', 'N', 'N'),
    (46_u32, "GetDead", 'N', 'N', 'N'),
    (47_u32, "GetItemCount", 'R', 'N', 'N'),
    (48_u32, "GetGold", 'N', 'N', 'N'),
    (49_u32, "GetSleeping", 'N', 'N', 'N'),
    (50_u32, "GetTalkedToPC", 'N', 'N', 'N'),
    (56_u32, "GetQuestRunning", 'R', 'N', 'N'),
    (58_u32, "GetStageCurrentInstance", 'N', 'N', 'N'),
    (59_u32, "GetStageDoneCurrentInstance", 'I', 'N', 'N'),
    (60_u32, "GetFactionRankDifference", 'R', 'R', 'N'),
    (61_u32, "GetAlarmed", 'N', 'N', 'N'),
    (62_u32, "IsRaining", 'R', 'N', 'N'),
    (63_u32, "GetAttacked", 'N', 'N', 'N'),
    (64_u32, "GetIsCreature", 'N', 'N', 'N'),
    (65_u32, "GetLockLevel", 'N', 'N', 'N'),
    (66_u32, "GetShouldAttack", 'R', 'N', 'N'),
    (67_u32, "GetInCell", 'R', 'N', 'N'),
    (68_u32, "GetIsClass", 'R', 'N', 'N'),
    (69_u32, "GetIsRace", 'R', 'N', 'N'),
    (70_u32, "GetIsSex", 'I', 'N', 'N'),
    (71_u32, "GetInFaction", 'R', 'N', 'N'),
    (72_u32, "GetIsID", 'R', 'N', 'N'),
    (73_u32, "GetFactionRank", 'R', 'N', 'N'),
    (74_u32, "GetGlobalValue", 'R', 'N', 'N'),
    (75_u32, "IsSnowing", 'R', 'N', 'N'),
    (77_u32, "GetRandomPercent", 'N', 'N', 'N'),
    (79_u32, "WouldBeStealing", 'R', 'N', 'N'),
    (80_u32, "GetLevel", 'N', 'N', 'N'),
    (81_u32, "IsRotating", 'N', 'N', 'N'),
    (84_u32, "GetDeadCount", 'R', 'N', 'N'),
    (91_u32, "GetIsAlerted", 'N', 'N', 'N'),
    (98_u32, "GetPlayerControlsDisabled", 'N', 'N', 'N'),
    (99_u32, "GetHeadingAngle", 'R', 'N', 'N'),
    (101_u32, "IsWeaponMagicOut", 'N', 'N', 'N'),
    (102_u32, "IsTorchOut", 'N', 'N', 'N'),
    (103_u32, "IsShieldOut", 'N', 'N', 'N'),
    (105_u32, "IsActionRef", 'R', 'N', 'N'),
    (106_u32, "IsFacingUp", 'N', 'N', 'N'),
    (107_u32, "GetKnockedState", 'N', 'N', 'N'),
    (108_u32, "GetWeaponAnimType", 'N', 'N', 'N'),
    (109_u32, "IsWeaponSkillType", 'A', 'N', 'N'),
    (110_u32, "GetCurrentAIPackage", 'N', 'N', 'N'),
    (111_u32, "IsWaiting", 'N', 'N', 'N'),
    (112_u32, "IsIdlePlaying", 'N', 'N', 'N'),
    (116_u32, "IsIntimidatedbyPlayer", 'N', 'N', 'N'),
    (117_u32, "IsPlayerInRegion", 'R', 'N', 'N'),
    (118_u32, "GetActorAggroRadiusViolated", 'N', 'N', 'N'),
    (122_u32, "GetCrime", 'R', 'I', 'N'),
    (123_u32, "IsGreetingPlayer", 'N', 'N', 'N'),
    (125_u32, "IsGuard", 'N', 'N', 'N'),
    (127_u32, "HasBeenEaten", 'N', 'N', 'N'),
    (128_u32, "GetStaminaPercentage", 'N', 'N', 'N'),
    (129_u32, "HasBeenRead", 'R', 'N', 'N'),
    (130_u32, "GetDying", 'N', 'N', 'N'),
    (131_u32, "GetSceneActionPercent", 'R', 'I', 'N'),
    (132_u32, "WouldRefuseCommand", 'R', 'N', 'N'),
    (133_u32, "SameFactionAsPC", 'N', 'N', 'N'),
    (134_u32, "SameRaceAsPC", 'N', 'N', 'N'),
    (135_u32, "SameSexAsPC", 'N', 'N', 'N'),
    (136_u32, "GetIsReference", 'R', 'N', 'N'),
    (141_u32, "IsTalking", 'N', 'N', 'N'),
    (142_u32, "GetComponentCount", 'R', 'N', 'N'),
    (143_u32, "GetCurrentAIProcedure", 'N', 'N', 'N'),
    (144_u32, "GetTrespassWarningLevel", 'N', 'N', 'N'),
    (145_u32, "IsTrespassing", 'N', 'N', 'N'),
    (146_u32, "IsInMyOwnedCell", 'N', 'N', 'N'),
    (147_u32, "GetWindSpeed", 'N', 'N', 'N'),
    (148_u32, "GetCurrentWeatherPercent", 'R', 'N', 'N'),
    (149_u32, "GetIsCurrentWeather", 'R', 'R', 'N'),
    (150_u32, "IsContinuingPackagePCNear", 'N', 'N', 'N'),
    (152_u32, "GetIsCrimeFaction", 'R', 'N', 'N'),
    (153_u32, "CanHaveFlames", 'N', 'N', 'N'),
    (154_u32, "HasFlames", 'N', 'N', 'N'),
    (157_u32, "GetOpenState", 'N', 'N', 'N'),
    (159_u32, "GetSitting", 'N', 'N', 'N'),
    (161_u32, "GetIsCurrentPackage", 'R', 'N', 'N'),
    (162_u32, "IsCurrentFurnitureRef", 'R', 'N', 'N'),
    (163_u32, "IsCurrentFurnitureObj", 'R', 'N', 'N'),
    (170_u32, "GetDayOfWeek", 'N', 'N', 'N'),
    (172_u32, "GetTalkedToPCParam", 'R', 'N', 'N'),
    (175_u32, "IsPCSleeping", 'N', 'N', 'N'),
    (176_u32, "IsPCAMurderer", 'N', 'N', 'N'),
    (180_u32, "HasSameEditorLocationAsRef", 'R', 'R', 'N'),
    (181_u32, "HasSameEditorLocationAsRefAlias", 'I', 'R', 'N'),
    (182_u32, "GetEquipped", 'R', 'N', 'N'),
    (185_u32, "IsSwimming", 'N', 'N', 'N'),
    (190_u32, "GetAmountSoldStolen", 'N', 'N', 'N'),
    (192_u32, "GetIgnoreCrime", 'N', 'N', 'N'),
    (193_u32, "GetPCExpelled", 'R', 'N', 'N'),
    (195_u32, "GetPCFactionMurder", 'R', 'N', 'N'),
    (197_u32, "GetPCEnemyofFaction", 'R', 'N', 'N'),
    (199_u32, "GetPCFactionAttack", 'R', 'N', 'N'),
    (203_u32, "GetDestroyed", 'N', 'N', 'N'),
    (214_u32, "HasMagicEffect", 'R', 'N', 'N'),
    (215_u32, "GetDefaultOpen", 'N', 'N', 'N'),
    (223_u32, "IsSpellTarget", 'R', 'N', 'N'),
    (224_u32, "GetVATSMode", 'N', 'N', 'N'),
    (225_u32, "GetPersuasionNumber", 'N', 'N', 'N'),
    (226_u32, "GetVampireFeed", 'N', 'N', 'N'),
    (227_u32, "GetCannibal", 'N', 'N', 'N'),
    (228_u32, "GetIsClassDefault", 'R', 'N', 'N'),
    (229_u32, "GetClassDefaultMatch", 'N', 'N', 'N'),
    (230_u32, "GetInCellParam", 'R', 'R', 'N'),
    (231_u32, "GetPlayerDialogueInput", 'N', 'N', 'N'),
    (235_u32, "GetVatsTargetHeight", 'N', 'N', 'N'),
    (237_u32, "GetIsGhost", 'N', 'N', 'N'),
    (242_u32, "GetUnconscious", 'N', 'N', 'N'),
    (244_u32, "GetRestrained", 'N', 'N', 'N'),
    (246_u32, "GetIsUsedItem", 'R', 'N', 'N'),
    (247_u32, "GetIsUsedItemType", 'I', 'N', 'N'),
    (248_u32, "IsScenePlaying", 'R', 'N', 'N'),
    (249_u32, "IsInDialogueWithPlayer", 'N', 'N', 'N'),
    (250_u32, "GetLocationCleared", 'R', 'N', 'N'),
    (254_u32, "GetIsPlayableRace", 'N', 'N', 'N'),
    (255_u32, "GetOffersServicesNow", 'N', 'N', 'N'),
    (258_u32, "HasAssociationType", 'R', 'R', 'N'),
    (259_u32, "HasFamilyRelationship", 'R', 'N', 'N'),
    (261_u32, "HasParentRelationship", 'R', 'N', 'N'),
    (262_u32, "IsWarningAbout", 'R', 'N', 'N'),
    (263_u32, "IsWeaponOut", 'N', 'N', 'N'),
    (264_u32, "HasSpell", 'R', 'N', 'N'),
    (265_u32, "IsTimePassing", 'N', 'N', 'N'),
    (266_u32, "IsPleasant", 'R', 'N', 'N'),
    (267_u32, "IsCloudy", 'R', 'N', 'N'),
    (274_u32, "IsSmallBump", 'N', 'N', 'N'),
    (276_u32, "IsInInteriorAcousticSpace", 'N', 'N', 'N'),
    (277_u32, "GetBaseValue", 'A', 'N', 'N'),
    (278_u32, "IsOwner", 'R', 'N', 'N'),
    (280_u32, "IsCellOwner", 'R', 'R', 'N'),
    (282_u32, "IsHorseStolen", 'N', 'N', 'N'),
    (285_u32, "IsLeftUp", 'N', 'N', 'N'),
    (286_u32, "IsSneaking", 'N', 'N', 'N'),
    (287_u32, "IsRunning", 'N', 'N', 'N'),
    (288_u32, "GetFriendHit", 'N', 'N', 'N'),
    (289_u32, "IsInCombat", 'I', 'N', 'N'),
    (300_u32, "IsInInterior", 'N', 'N', 'N'),
    (304_u32, "IsWaterObject", 'N', 'N', 'N'),
    (305_u32, "GetPlayerAction", 'N', 'N', 'N'),
    (306_u32, "IsActorUsingATorch", 'N', 'N', 'N'),
    (309_u32, "IsXBox", 'N', 'N', 'N'),
    (310_u32, "GetInWorldspace", 'I', 'N', 'N'),
    (312_u32, "GetPCMiscStat", 'I', 'N', 'N'),
    (313_u32, "GetPairedAnimation", 'N', 'N', 'N'),
    (314_u32, "IsActorAVictim", 'N', 'N', 'N'),
    (315_u32, "GetTotalPersuasionNumber", 'N', 'N', 'N'),
    (318_u32, "GetIdleDoneOnce", 'N', 'N', 'N'),
    (320_u32, "GetNoRumors", 'N', 'N', 'N'),
    (323_u32, "GetCombatState", 'N', 'N', 'N'),
    (325_u32, "GetWithinPackageLocation", 'I', 'N', 'N'),
    (327_u32, "IsRidingMount", 'N', 'N', 'N'),
    (329_u32, "IsFleeing", 'N', 'N', 'N'),
    (332_u32, "IsInDangerousWater", 'N', 'N', 'N'),
    (338_u32, "GetIgnoreFriendlyHits", 'N', 'N', 'N'),
    (339_u32, "IsPlayersLastRiddenMount", 'N', 'N', 'N'),
    (353_u32, "IsActor", 'N', 'N', 'N'),
    (354_u32, "IsEssential", 'N', 'N', 'N'),
    (358_u32, "IsPlayerMovingIntoNewSpace", 'N', 'N', 'N'),
    (359_u32, "GetInCurrentLocation", 'R', 'N', 'N'),
    (360_u32, "GetInCurrentLocationAlias", 'I', 'N', 'N'),
    (361_u32, "GetTimeDead", 'N', 'N', 'N'),
    (362_u32, "HasLinkedRef", 'R', 'N', 'N'),
    (365_u32, "IsChild", 'N', 'N', 'N'),
    (366_u32, "GetStolenItemValueNoCrime", 'R', 'N', 'N'),
    (367_u32, "GetLastPlayerAction", 'N', 'N', 'N'),
    (368_u32, "IsPlayerActionActive", 'I', 'N', 'N'),
    (370_u32, "IsTalkingActivatorActor", 'R', 'N', 'N'),
    (371_u32, "IsOnChems", 'N', 'N', 'N'),
    (372_u32, "IsInList", 'R', 'N', 'N'),
    (373_u32, "GetStolenItemValue", 'R', 'N', 'N'),
    (375_u32, "GetCrimeGoldViolent", 'R', 'N', 'N'),
    (376_u32, "GetCrimeGoldNonviolent", 'R', 'N', 'N'),
    (378_u32, "IsOwnedBy", 'R', 'N', 'N'),
    (380_u32, "GetCommandDistance", 'N', 'N', 'N'),
    (381_u32, "GetCommandLocationDistance", 'N', 'N', 'N'),
    (390_u32, "GetHitLocation", 'N', 'N', 'N'),
    (391_u32, "IsPC1stPerson", 'N', 'N', 'N'),
    (396_u32, "GetCauseofDeath", 'N', 'N', 'N'),
    (397_u32, "IsLimbGone", 'I', 'N', 'N'),
    (398_u32, "IsWeaponInList", 'R', 'N', 'N'),
    (402_u32, "IsBribedbyPlayer", 'N', 'N', 'N'),
    (403_u32, "GetRelationshipRank", 'R', 'N', 'N'),
    (407_u32, "GetVATSValue", 'I', 'I', 'N'),
    (408_u32, "IsKiller", 'R', 'N', 'N'),
    (409_u32, "IsKillerObject", 'R', 'N', 'N'),
    (410_u32, "GetFactionCombatReaction", 'R', 'R', 'N'),
    (414_u32, "Exists", 'R', 'N', 'N'),
    (415_u32, "GetGroupMemberCount", 'N', 'N', 'N'),
    (416_u32, "GetGroupTargetCount", 'N', 'N', 'N'),
    (426_u32, "GetIsVoiceType", 'R', 'N', 'N'),
    (427_u32, "GetPlantedExplosive", 'N', 'N', 'N'),
    (429_u32, "IsScenePackageRunning", 'N', 'N', 'N'),
    (430_u32, "GetHealthPercentage", 'N', 'N', 'N'),
    (432_u32, "GetIsObjectType", 'I', 'N', 'N'),
    (434_u32, "PlayerVisualDetection", 'N', 'N', 'N'),
    (435_u32, "PlayerAudioDetection", 'N', 'N', 'N'),
    (437_u32, "GetIsCreatureType", 'I', 'N', 'N'),
    (438_u32, "HasKey", 'R', 'N', 'N'),
    (439_u32, "IsFurnitureEntryType", 'I', 'N', 'N'),
    (444_u32, "GetInCurrentLocationFormList", 'R', 'N', 'N'),
    (445_u32, "GetInZone", 'R', 'N', 'N'),
    (446_u32, "GetVelocity", 'I', 'N', 'N'),
    (447_u32, "GetGraphVariableFloat", 'S', 'N', 'N'),
    (448_u32, "HasPerk", 'R', 'N', 'N'),
    (449_u32, "GetFactionRelation", 'R', 'N', 'N'),
    (450_u32, "IsLastIdlePlayed", 'R', 'N', 'N'),
    (453_u32, "GetPlayerTeammate", 'N', 'N', 'N'),
    (454_u32, "GetPlayerTeammateCount", 'N', 'N', 'N'),
    (458_u32, "GetActorCrimePlayerEnemy", 'N', 'N', 'N'),
    (459_u32, "GetCrimeGold", 'R', 'N', 'N'),
    (463_u32, "IsPlayerGrabbedRef", 'R', 'N', 'N'),
    (465_u32, "GetKeywordItemCount", 'R', 'N', 'N'),
    (470_u32, "GetDestructionStage", 'N', 'N', 'N'),
    (473_u32, "GetIsAlignment", 'I', 'N', 'N'),
    (476_u32, "IsProtected", 'N', 'N', 'N'),
    (477_u32, "GetThreatRatio", 'R', 'N', 'N'),
    (479_u32, "GetIsUsedItemEquipType", 'R', 'N', 'N'),
    (483_u32, "GetPlayerActivated", 'N', 'N', 'N'),
    (485_u32, "GetFullyEnabledActorsInHigh", 'N', 'N', 'N'),
    (487_u32, "IsCarryable", 'N', 'N', 'N'),
    (488_u32, "GetConcussed", 'N', 'N', 'N'),
    (491_u32, "GetMapMarkerVisible", 'N', 'N', 'N'),
    (493_u32, "PlayerKnows", 'R', 'N', 'N'),
    (494_u32, "GetPermanentValue", 'A', 'N', 'N'),
    (495_u32, "GetKillingBlowLimb", 'N', 'N', 'N'),
    (497_u32, "CanPayCrimeGold", 'R', 'N', 'N'),
    (499_u32, "GetDaysInJail", 'N', 'N', 'N'),
    (500_u32, "EPAlchemyGetMakingPoison", 'N', 'N', 'N'),
    (501_u32, "EPAlchemyEffectHasKeyword", 'R', 'N', 'N'),
    (503_u32, "GetAllowWorldInteractions", 'N', 'N', 'N'),
    (506_u32, "DialogueGetAv", 'A', 'N', 'N'),
    (507_u32, "DialogueHasPerk", 'R', 'N', 'N'),
    (508_u32, "GetLastHitCritical", 'N', 'N', 'N'),
    (510_u32, "DialogueGetItemCount", 'R', 'N', 'N'),
    (511_u32, "LastCrippledCondition", 'A', 'N', 'N'),
    (512_u32, "HasSharedPowerGrid", 'R', 'N', 'N'),
    (513_u32, "IsCombatTarget", 'R', 'N', 'N'),
    (515_u32, "GetVATSRightAreaFree", 'R', 'N', 'N'),
    (516_u32, "GetVATSLeftAreaFree", 'R', 'N', 'N'),
    (517_u32, "GetVATSBackAreaFree", 'R', 'N', 'N'),
    (518_u32, "GetVATSFrontAreaFree", 'R', 'N', 'N'),
    (519_u32, "GetIsLockBroken", 'N', 'N', 'N'),
    (520_u32, "IsPS3", 'N', 'N', 'N'),
    (521_u32, "IsWindowsPC", 'N', 'N', 'N'),
    (522_u32, "GetVATSRightTargetVisible", 'R', 'N', 'N'),
    (523_u32, "GetVATSLeftTargetVisible", 'R', 'N', 'N'),
    (524_u32, "GetVATSBackTargetVisible", 'R', 'N', 'N'),
    (525_u32, "GetVATSFrontTargetVisible", 'R', 'N', 'N'),
    (528_u32, "IsInCriticalStage", 'I', 'N', 'N'),
    (530_u32, "GetXPForNextLevel", 'N', 'N', 'N'),
    (533_u32, "GetInfamy", 'R', 'N', 'N'),
    (534_u32, "GetInfamyViolent", 'R', 'N', 'N'),
    (535_u32, "GetInfamyNonViolent", 'R', 'N', 'N'),
    (536_u32, "GetTypeCommandPerforming", 'N', 'N', 'N'),
    (543_u32, "GetQuestCompleted", 'R', 'N', 'N'),
    (544_u32, "GetSpeechChallengeSuccessLevel", 'N', 'N', 'N'),
    (547_u32, "IsGoreDisabled", 'N', 'N', 'N'),
    (550_u32, "IsSceneActionComplete", 'R', 'I', 'N'),
    (552_u32, "GetSpellUsageNum", 'R', 'N', 'N'),
    (554_u32, "GetActorsInHigh", 'N', 'N', 'N'),
    (555_u32, "HasLoaded3D", 'N', 'N', 'N'),
    (560_u32, "HasKeyword", 'R', 'N', 'N'),
    (561_u32, "HasRefType", 'R', 'N', 'N'),
    (562_u32, "LocationHasKeyword", 'R', 'N', 'N'),
    (563_u32, "LocationHasRefType", 'R', 'N', 'N'),
    (565_u32, "GetIsEditorLocation", 'R', 'N', 'N'),
    (566_u32, "GetIsAliasRef", 'I', 'N', 'N'),
    (567_u32, "GetIsEditorLocationAlias", 'I', 'N', 'N'),
    (568_u32, "IsSprinting", 'N', 'N', 'N'),
    (569_u32, "IsBlocking", 'N', 'N', 'N'),
    (570_u32, "HasEquippedSpell", 'I', 'N', 'N'),
    (571_u32, "GetCurrentCastingType", 'I', 'N', 'N'),
    (572_u32, "GetCurrentDeliveryType", 'I', 'N', 'N'),
    (574_u32, "GetAttackState", 'N', 'N', 'N'),
    (576_u32, "GetEventData", 'I', 'R', 'S'),
    (577_u32, "IsCloserToAThanB", 'R', 'R', 'N'),
    (578_u32, "LevelMinusPCLevel", 'N', 'N', 'N'),
    (579_u32, "EditorLocationHasKeyword", 'R', 'N', 'N'),
    (580_u32, "IsBleedingOut", 'N', 'N', 'N'),
    (584_u32, "GetRelativeAngle", 'R', 'I', 'N'),
    (589_u32, "GetMovementDirection", 'N', 'N', 'N'),
    (590_u32, "IsInScene", 'N', 'N', 'N'),
    (591_u32, "GetRefTypeDeadCount", 'R', 'R', 'N'),
    (592_u32, "GetRefTypeAliveCount", 'R', 'R', 'N'),
    (594_u32, "GetIsFlying", 'N', 'N', 'N'),
    (595_u32, "IsCurrentSpell", 'R', 'I', 'N'),
    (596_u32, "SpellHasKeyword", 'R', 'N', 'N'),
    (597_u32, "GetEquippedItemType", 'I', 'N', 'N'),
    (598_u32, "GetLocationAliasCleared", 'I', 'N', 'N'),
    (600_u32, "GetLocationAliasRefTypeDeadCount", 'I', 'R', 'N'),
    (601_u32, "GetLocationAliasRefTypeAliveCount", 'I', 'R', 'N'),
    (602_u32, "IsWardState", 'I', 'N', 'N'),
    (603_u32, "IsInSameCurrentLocationAsRef", 'R', 'R', 'N'),
    (604_u32, "IsInSameCurrentLocationAsRefAlias", 'I', 'R', 'N'),
    (605_u32, "LocationAliasIsLocation", 'I', 'R', 'N'),
    (606_u32, "GetKeywordDataForLocation", 'R', 'R', 'N'),
    (608_u32, "GetKeywordDataForAlias", 'I', 'R', 'N'),
    (610_u32, "LocationAliasHasKeyword", 'I', 'R', 'N'),
    (611_u32, "IsNullPackageData", 'I', 'N', 'N'),
    (612_u32, "GetNumericPackageData", 'I', 'N', 'N'),
    (613_u32, "IsPlayerRadioOn", 'N', 'N', 'N'),
    (614_u32, "GetPlayerRadioFrequency", 'N', 'N', 'N'),
    (615_u32, "GetHighestRelationshipRank", 'N', 'N', 'N'),
    (616_u32, "GetLowestRelationshipRank", 'N', 'N', 'N'),
    (617_u32, "HasAssociationTypeAny", 'R', 'N', 'N'),
    (618_u32, "HasFamilyRelationshipAny", 'N', 'N', 'N'),
    (619_u32, "GetPathingTargetOffset", 'I', 'N', 'N'),
    (620_u32, "GetPathingTargetAngleOffset", 'I', 'N', 'N'),
    (621_u32, "GetPathingTargetSpeed", 'N', 'N', 'N'),
    (622_u32, "GetPathingTargetSpeedAngle", 'I', 'N', 'N'),
    (623_u32, "GetMovementSpeed", 'N', 'N', 'N'),
    (624_u32, "GetInContainer", 'R', 'N', 'N'),
    (625_u32, "IsLocationLoaded", 'R', 'N', 'N'),
    (626_u32, "IsLocationAliasLoaded", 'I', 'N', 'N'),
    (627_u32, "IsDualCasting", 'N', 'N', 'N'),
    (629_u32, "GetVMQuestVariable", 'R', 'S', 'N'),
    (630_u32, "GetCombatAudioDetection", 'N', 'N', 'N'),
    (631_u32, "GetCombatVisualDetection", 'N', 'N', 'N'),
    (632_u32, "IsCasting", 'N', 'N', 'N'),
    (633_u32, "GetFlyingState", 'N', 'N', 'N'),
    (635_u32, "IsInFavorState", 'N', 'N', 'N'),
    (636_u32, "HasTwoHandedWeaponEquipped", 'N', 'N', 'N'),
    (637_u32, "IsFurnitureExitType", 'I', 'N', 'N'),
    (638_u32, "IsInFriendStatewithPlayer", 'N', 'N', 'N'),
    (639_u32, "GetWithinDistance", 'R', 'F', 'N'),
    (640_u32, "GetValuePercent", 'A', 'N', 'N'),
    (641_u32, "IsUnique", 'N', 'N', 'N'),
    (642_u32, "GetLastBumpDirection", 'N', 'N', 'N'),
    (644_u32, "GetInfoChallangeSuccess", 'N', 'N', 'N'),
    (645_u32, "GetIsInjured", 'N', 'N', 'N'),
    (646_u32, "GetIsCrashLandRequest", 'N', 'N', 'N'),
    (647_u32, "GetIsHastyLandRequest", 'N', 'N', 'N'),
    (650_u32, "IsLinkedTo", 'R', 'R', 'N'),
    (651_u32, "GetKeywordDataForCurrentLocation", 'R', 'N', 'N'),
    (652_u32, "GetInSharedCrimeFaction", 'R', 'N', 'N'),
    (654_u32, "GetBribeSuccess", 'N', 'N', 'N'),
    (655_u32, "GetIntimidateSuccess", 'N', 'N', 'N'),
    (656_u32, "GetArrestedState", 'N', 'N', 'N'),
    (657_u32, "GetArrestingActor", 'N', 'N', 'N'),
    (659_u32, "HasVMScript", 'S', 'N', 'N'),
    (660_u32, "GetVMScriptVariable", 'S', 'S', 'N'),
    (661_u32, "GetWorkshopResourceDamage", 'A', 'N', 'N'),
    (664_u32, "HasValidRumorTopic", 'R', 'N', 'N'),
    (672_u32, "IsAttacking", 'N', 'N', 'N'),
    (673_u32, "IsPowerAttacking", 'N', 'N', 'N'),
    (674_u32, "IsLastHostileActor", 'N', 'N', 'N'),
    (675_u32, "GetGraphVariableInt", 'S', 'N', 'N'),
    (678_u32, "ShouldAttackKill", 'R', 'N', 'N'),
    (680_u32, "GetActivationHeight", 'N', 'N', 'N'),
    (682_u32, "WornHasKeyword", 'R', 'N', 'N'),
    (683_u32, "GetPathingCurrentSpeed", 'N', 'N', 'N'),
    (684_u32, "GetPathingCurrentSpeedAngle", 'I', 'N', 'N'),
    (691_u32, "GetWorkshopObjectCount", 'R', 'N', 'N'),
    (692_u32, "GetStrongestEnemyHasKeyword", 'R', 'N', 'N'),
    (693_u32, "EPMagic_SpellHasKeyword", 'R', 'N', 'N'),
    (694_u32, "GetNoBleedoutRecovery", 'N', 'N', 'N'),
    (696_u32, "EPMagic_SpellHasSkill", 'A', 'N', 'N'),
    (697_u32, "IsAttackType", 'R', 'N', 'N'),
    (698_u32, "IsAllowedToFly", 'N', 'N', 'N'),
    (699_u32, "HasMagicEffectKeyword", 'R', 'N', 'N'),
    (700_u32, "IsCommandedActor", 'N', 'N', 'N'),
    (701_u32, "IsStaggered", 'N', 'N', 'N'),
    (702_u32, "IsRecoiling", 'N', 'N', 'N'),
    (703_u32, "HasScopeWeaponEquipped", 'N', 'N', 'N'),
    (704_u32, "IsPathing", 'N', 'N', 'N'),
    (705_u32, "GetShouldHelp", 'R', 'N', 'N'),
    (706_u32, "HasBoundWeaponEquipped", 'I', 'N', 'N'),
    (707_u32, "GetCombatTargetHasKeyword", 'R', 'N', 'N'),
    (709_u32, "GetCombatGroupMemberCount", 'N', 'N', 'N'),
    (710_u32, "IsIgnoringCombat", 'N', 'N', 'N'),
    (711_u32, "GetLightLevel", 'N', 'N', 'N'),
    (713_u32, "SpellHasCastingPerk", 'R', 'N', 'N'),
    (714_u32, "IsBeingRidden", 'N', 'N', 'N'),
    (715_u32, "IsUndead", 'N', 'N', 'N'),
    (716_u32, "GetRealHoursPassed", 'N', 'N', 'N'),
    (718_u32, "IsUnlockedDoor", 'N', 'N', 'N'),
    (719_u32, "IsHostileToActor", 'R', 'N', 'N'),
    (720_u32, "GetTargetHeight", 'R', 'N', 'N'),
    (721_u32, "IsPoison", 'N', 'N', 'N'),
    (722_u32, "WornApparelHasKeywordCount", 'R', 'N', 'N'),
    (723_u32, "GetItemHealthPercent", 'N', 'N', 'N'),
    (724_u32, "EffectWasDualCast", 'N', 'N', 'N'),
    (725_u32, "GetKnockStateEnum", 'N', 'N', 'N'),
    (726_u32, "DoesNotExist", 'N', 'N', 'N'),
    (728_u32, "GetPlayerWalkAwayFromDialogueScene", 'N', 'N', 'N'),
    (729_u32, "GetActorStance", 'N', 'N', 'N'),
    (730_u32, "HasAnyMutatedTeammates", 'N', 'N', 'N'),
    (734_u32, "CanProduceForWorkshop", 'N', 'N', 'N'),
    (735_u32, "CanFlyHere", 'N', 'N', 'N'),
    (736_u32, "EPIsDamageType", 'R', 'N', 'N'),
    (737_u32, "GetCurrentWeatherHasKeyword", 'R', 'N', 'N'),
    (738_u32, "GetActorGunState", 'N', 'N', 'N'),
    (739_u32, "GetVoiceLineLength", 'N', 'N', 'N'),
    (741_u32, "ObjectTemplateItem_HasKeyword", 'R', 'N', 'N'),
    (742_u32, "ObjectTemplateItem_HasUniqueKeyword", 'R', 'N', 'N'),
    (743_u32, "ObjectTemplateItem_GetLevel", 'N', 'N', 'N'),
    (744_u32, "MovementIdleMatches", 'I', 'I', 'N'),
    (745_u32, "GetActionData", 'N', 'N', 'N'),
    (746_u32, "GetActionDataShort", 'I', 'N', 'N'),
    (747_u32, "GetActionDataByte", 'I', 'N', 'N'),
    (748_u32, "GetActionDataFlag", 'I', 'N', 'N'),
    (749_u32, "ModdedItemHasKeyword", 'R', 'N', 'N'),
    (750_u32, "GetAngryWithPlayer", 'N', 'N', 'N'),
    (751_u32, "IsCameraUnderWater", 'N', 'N', 'N'),
    (753_u32, "IsActorRefOwner", 'R', 'N', 'N'),
    (754_u32, "HasActorRefOwner", 'R', 'N', 'N'),
    (756_u32, "GetLoadedAmmoCount", 'N', 'N', 'N'),
    (757_u32, "IsTimeSpanSunrise", 'N', 'N', 'N'),
    (758_u32, "IsTimeSpanMorning", 'N', 'N', 'N'),
    (759_u32, "IsTimeSpanAfternoon", 'N', 'N', 'N'),
    (760_u32, "IsTimeSpanEvening", 'N', 'N', 'N'),
    (761_u32, "IsTimeSpanSunset", 'N', 'N', 'N'),
    (762_u32, "IsTimeSpanNight", 'N', 'N', 'N'),
    (763_u32, "IsTimeSpanMidnight", 'N', 'N', 'N'),
    (764_u32, "IsTimeSpanAnyDay", 'N', 'N', 'N'),
    (765_u32, "IsTimeSpanAnyNight", 'N', 'N', 'N'),
    (766_u32, "CurrentFurnitureHasKeyword", 'R', 'N', 'N'),
    (767_u32, "GetWeaponEquipIndex", 'N', 'N', 'N'),
    (769_u32, "IsOverEncumbered", 'N', 'N', 'N'),
    (770_u32, "IsPackageRequestingBlockedIdles", 'N', 'N', 'N'),
    (771_u32, "GetActionDataInt", 'N', 'N', 'N'),
    (772_u32, "GetVATSRightMinusLeftAreaFree", 'R', 'N', 'N'),
    (773_u32, "GetInIronSights", 'R', 'N', 'N'),
    (774_u32, "GetActorStaggerDirection", 'N', 'N', 'N'),
    (775_u32, "GetActorStaggerMagnitude", 'N', 'N', 'N'),
    (776_u32, "WornCoversBipedSlot", 'I', 'N', 'N'),
    (777_u32, "GetInventoryValue", 'N', 'N', 'N'),
    (778_u32, "IsPlayerInConversation", 'N', 'N', 'N'),
    (779_u32, "IsInDialogueCamera", 'N', 'N', 'N'),
    (780_u32, "IsMyDialogueTargetPlayer", 'N', 'N', 'N'),
    (781_u32, "IsMyDialogueTargetActor", 'N', 'N', 'N'),
    (782_u32, "GetMyDialogueTargetDistance", 'N', 'N', 'N'),
    (783_u32, "IsSeatOccupied", 'R', 'N', 'N'),
    (784_u32, "IsPlayerRiding", 'N', 'N', 'N'),
    (785_u32, "IsTryingEventCamera", 'N', 'N', 'N'),
    (786_u32, "UseLeftSideCamera", 'N', 'N', 'N'),
    (787_u32, "GetNoteType", 'N', 'N', 'N'),
    (788_u32, "LocationHasPlayerOwnedWorkshop", 'N', 'N', 'N'),
    (789_u32, "IsStartingAction", 'N', 'N', 'N'),
    (790_u32, "IsMidAction", 'N', 'N', 'N'),
    (791_u32, "IsWeaponChargeAttack", 'N', 'N', 'N'),
    (792_u32, "IsInWorkshopMode", 'N', 'N', 'N'),
    (793_u32, "IsWeaponChargingHoldAttack", 'N', 'N', 'N'),
    (794_u32, "IsEncounterAbovePlayerLevel", 'N', 'N', 'N'),
    (795_u32, "IsMeleeAttacking", 'N', 'N', 'N'),
    (796_u32, "GetVATSQueuedTargetsUnique", 'N', 'N', 'N'),
    (797_u32, "GetCurrentLocationCleared", 'N', 'N', 'N'),
    (798_u32, "IsPowered", 'N', 'N', 'N'),
    (799_u32, "GetTransmitterDistance", 'N', 'N', 'N'),
    (800_u32, "GetCameraPlaybackTime", 'N', 'N', 'N'),
    (801_u32, "IsInWater", 'N', 'N', 'N'),
    (802_u32, "GetWithinActivateDistance", 'R', 'N', 'N'),
    (803_u32, "IsUnderWater", 'N', 'N', 'N'),
    (804_u32, "IsInSameSpace", 'R', 'N', 'N'),
    (805_u32, "LocationAllowsReset", 'N', 'N', 'N'),
    (806_u32, "GetVATSBackRightAreaFree", 'R', 'N', 'N'),
    (807_u32, "GetVATSBackLeftAreaFree", 'R', 'N', 'N'),
    (808_u32, "GetVATSBackRightTargetVisible", 'R', 'N', 'N'),
    (809_u32, "GetVATSBackLeftTargetVisible", 'R', 'N', 'N'),
    (810_u32, "GetVATSTargetLimbVisible", 'R', 'N', 'N'),
    (811_u32, "IsPlayerListening", 'F', 'N', 'N'),
    (812_u32, "GetPathingRequestedQuickTurn", 'N', 'N', 'N'),
    (813_u32, "EPIsCalculatingBaseDamage", 'N', 'N', 'N'),
    (814_u32, "GetReanimating", 'N', 'N', 'N'),
    (817_u32, "IsInRobotWorkbench", 'N', 'N', 'N'),
    (818_u32, "IsActorsTurfActive", 'N', 'N', 'N'),
    (828_u32, "GetIsPlayer", 'N', 'N', 'N'),
    (832_u32, "GetStageUniqueQuest", 'R', 'N', 'N'),
    (833_u32, "GetStageDoneUniqueQuest", 'R', 'I', 'N'),
    (834_u32, "GetVMQuestVariableUnique", 'R', 'S', 'N'),
    (835_u32, "IsWorkshopOwner", 'R', 'N', 'N'),
    (836_u32, "IsWorkshopClaimant", 'R', 'N', 'N'),
    (837_u32, "IsActivePlayer", 'N', 'N', 'N'),
    (839_u32, "IsMemberOfAPlayerTeam", 'N', 'N', 'N'),
    (840_u32, "IsWaterConsumeSpell", 'R', 'N', 'N'),
    (841_u32, "IsWaterContactSpell", 'R', 'N', 'N'),
    (842_u32, "IsPlayerInFriendlyWorkshop", 'N', 'N', 'N'),
    (843_u32, "GetJunkItemCount", 'N', 'N', 'N'),
    (844_u32, "GetIsCurrentLocationExact", 'R', 'N', 'N'),
    (845_u32, "GetIsEditorLocationExact", 'R', 'N', 'N'),
    (846_u32, "GetActorValueForCurrentLocation", 'A', 'R', 'N'),
    (849_u32, "GetIsInRegion", 'R', 'N', 'N'),
    (850_u32, "GetInAcousticSpace", 'R', 'N', 'N'),
    (851_u32, "IsPowerArmorOwner", 'N', 'N', 'N'),
    (852_u32, "GetCurrency", 'R', 'N', 'N'),
    (853_u32, "HasLearnedRecipe", 'R', 'N', 'N'),
    (854_u32, "HasActiveMagicEffect", 'R', 'N', 'N'),
    (855_u32, "HasBeenSearched", 'N', 'N', 'N'),
    (856_u32, "GetQuestRunningUnique", 'R', 'N', 'N'),
    (857_u32, "GetNumTimesCompletedQuest", 'R', 'N', 'N'),
    (858_u32, "WorkshopOwnerHasPerk", 'R', 'N', 'N'),
    (859_u32, "HasEntitlement", 'R', 'N', 'N'),
    (860_u32, "IsQuickplayer", 'N', 'N', 'N'),
    (861_u32, "IsVisitor", 'N', 'N', 'N'),
    (862_u32, "IsInWorkshop", 'N', 'N', 'N'),
    (863_u32, "IsInWorkshopOwned", 'R', 'N', 'N'),
    (864_u32, "IsJunkItem", 'N', 'N', 'N'),
    (865_u32, "IsInWeather", 'R', 'N', 'N'),
    (867_u32, "GetQuickplayModeLoadingInto", 'N', 'N', 'N'),
    (868_u32, "IsInitiatingFastTravel", 'N', 'N', 'N'),
    (869_u32, "GetQuickplayKeywordLoadingInto", 'R', 'N', 'N'),
    (870_u32, "GetNumActiveEffectsWithKeyword", 'R', 'N', 'N'),
    (871_u32, "GetNumActiveSpellsWithKeyword", 'R', 'N', 'N'),
    (872_u32, "GatLastHitHealthDamageAmount", 'N', 'N', 'N'),
    (873_u32, "GatLastHitTotalDamageAmount", 'N', 'N', 'N'),
    (874_u32, "GatLastHitDamageSourceType", 'N', 'N', 'N'),
    (875_u32, "IsTrueForConditionForm", 'R', 'N', 'N'),
    (876_u32, "IsActiveQuest", 'R', 'N', 'N'),
    (877_u32, "IsFullHealth", 'N', 'N', 'N'),
    (878_u32, "CHAL_IsTargetWeaponMelee", 'N', 'N', 'N'),
    (879_u32, "CHAL_IsTargetWeaponRanged", 'N', 'N', 'N'),
    (880_u32, "CHAL_IsTargetWeaponThrown", 'N', 'N', 'N'),
    (881_u32, "CHAL_GetTargetWeaponDamageType", 'R', 'N', 'N'),
    (882_u32, "CHAL_DoesTargetWeaponHaveKeyword", 'R', 'N', 'N'),
    (884_u32, "CHAL_IsTargetWorkshopRecipeInCategory", 'R', 'N', 'N'),
    (885_u32, "GetLastFallDamage", 'N', 'N', 'N'),
    (886_u32, "IsPlayerInCamp", 'N', 'N', 'N'),
    (887_u32, "GetLastHitLethal", 'N', 'N', 'N'),
    (888_u32, "IsPlayerTeammate", 'N', 'N', 'N'),
    (889_u32, "IsPlayerCombatOpponent", 'N', 'N', 'N'),
    (890_u32, "HasPerkCardEquipped", 'R', 'I', 'N'),
    (891_u32, "HasPerkCardFromListEquipped", 'R', 'N', 'N'),
    (892_u32, "GetLastCompletedCheckpointStage", 'N', 'N', 'N'),
    (893_u32, "IsPreviousMeleeAttackEvent", 'I', 'N', 'N'),
    (894_u32, "HasCompletedCheckpointStage", 'I', 'N', 'N'),
    (895_u32, "DoesRecipeContainObject", 'R', 'N', 'N'),
    (896_u32, "IsDailyCooldownExpired", 'A', 'N', 'N'),
    (897_u32, "GetRandomUInt", 'I', 'I', 'N'),
    (898_u32, "GetWorldType", 'N', 'N', 'N'),
    (899_u32, "IsEngagedInPvP", 'N', 'N', 'N'),
    (900_u32, "IsAggresive", 'N', 'N', 'N'),
    (901_u32, "IsInWorkshopPublic", 'N', 'N', 'N'),
    (902_u32, "IsPlayerInCampOwned", 'N', 'N', 'N'),
    (903_u32, "IsPlayerInCampTeam", 'N', 'N', 'N'),
    (904_u32, "CHAL_IsTargetWorkshopRecipe", 'R', 'N', 'N'),
    (905_u32, "DoesModApplyKeyword", 'R', 'N', 'N'),
    (906_u32, "HasCompletedChallenge", 'R', 'N', 'N'),
    (907_u32, "GetNumElementsInRefCollection", 'I', 'N', 'N'),
    (908_u32, "IsTeamLeader", 'N', 'N', 'N'),
    (909_u32, "ActorPackageHasRandomConversationsFlagOn", 'N', 'N', 'N'),
    (910_u32, "IsInInstancedLocation", 'N', 'N', 'N'),
    (911_u32, "IsInstanceOwner", 'R', 'N', 'N'),
    (914_u32, "IsQuestTracked", 'R', 'N', 'N'),
    (915_u32, "IsPlayerFO1Member", 'N', 'N', 'N'),
    (916_u32, "IsServerOverEWSActorBudget", 'N', 'N', 'N'),
    (917_u32, "GetStageDonePlayerInstance", 'R', 'I', 'N'),
    (918_u32, "IsAuthoritativeOverMovement", 'N', 'N', 'N'),
    (919_u32, "IsWeaponMinChargeTimeElapsed", 'N', 'N', 'N'),
    (920_u32, "IsOccupiedFurnitureRef", 'R', 'N', 'N'),
    (921_u32, "IsOccupiedFurnitureObj", 'R', 'N', 'N'),
    (922_u32, "GetTeammateBondScore", 'N', 'N', 'N'),
    (923_u32, "GetTeamType", 'N', 'N', 'N'),
    (924_u32, "GetNumPlayersInSameInterior", 'N', 'N', 'N'),
    (925_u32, "GetQuestFormType", 'N', 'N', 'N'),
    (926_u32, "GetPlayerSeasonRank", 'N', 'N', 'N'),
    (927_u32, "IsInWorkshopFreeCameraMode", 'N', 'N', 'N'),
    (928_u32, "IsVendor", 'N', 'N', 'N'),
    (929_u32, "GetLanguage", 'N', 'N', 'N'),
    (930_u32, "IsNextClipLastShot", 'N', 'N', 'N'),
    (931_u32, "WornInOrOutOfPowerArmorHasKeyword", 'R', 'N', 'N'),
    (932_u32, "IsPlayerInBestBuildCamp", 'N', 'N', 'N'),
    (933_u32, "GetLastHitLimbDamageMultiplier", 'N', 'N', 'N'),
    (934_u32, "IsLastDamageFromVATS", 'N', 'N', 'N'),
    (935_u32, "IsLastDamageCripplingLimb", 'N', 'N', 'N'),
    (936_u32, "GetCurrentCAMPWeatherHasKeyword", 'R', 'N', 'N'),
    (937_u32, "GetCurrentWeatherOverrideHasKeyword", 'R', 'N', 'N'),
    (938_u32, "HasActiveChallenge", 'R', 'N', 'N'),
    (5000_u32, "IsInAirOrFloating", 'N', 'N', 'N'),
    (5001_u32, "GetIsForm", 'R', 'N', 'N'),
    (5002_u32, "GetIsInDailyOps", 'N', 'N', 'N'),
    (5003_u32, "GetRadsHealthPercentage", 'N', 'N', 'N'),
    (5004_u32, "PlayerHasQuest", 'R', 'N', 'N'),
    (5005_u32, "IsBackpackVisible", 'N', 'N', 'N'),
    (5006_u32, "GetIsInExpedition", 'N', 'N', 'N'),
    (5007_u32, "HasCAMPWeatherActive", 'N', 'N', 'N'),
    (6000_u32, "GetSecondsSinceLastAttack", 'N', 'N', 'N'),
    (8000_u32, "IsDailyContentAvailable", 'N', 'N', 'N'),
    (8001_u32, "StartDailyContent", 'N', 'N', 'N'),
    (8002_u32, "GetRemainingQuestTimeSeconds", 'N', 'N', 'N'),
    (8003_u32, "IsCaravanAvailable", 'R', 'N', 'N'),
    (8004_u32, "CanFishHere", 'N', 'N', 'N'),
    (8005_u32, "IsFishingBaitSelected", 'R', 'N', 'N'),
    (8006_u32, "GetDepthInwater", 'N', 'N', 'N'),
    (8007_u32, "LocationHierarchyHasKeyword", 'R', 'N', 'N'),
    (9000_u32, "RemoveAchievement", 'I', 'N', 'N'),
    (9001_u32, "IsPlayerInShelterOwned", 'N', 'N', 'N'),
    (9002_u32, "IsPlayerInShelter", 'N', 'N', 'N'),
    (9003_u32, "IsInShelterLocation", 'N', 'N', 'N'),
    (9004_u32, "StopAllPublicEvents", 'N', 'N', 'N'),
    (9005_u32, "IsFalloutWorlds", 'N', 'N', 'N'),
    (10000_u32, "IsChallengeTypeDaily", 'N', 'N', 'N'),
    (10001_u32, "IsChallengeTypeWeekly", 'N', 'N', 'N'),
    (10002_u32, "IsChallengeTypeLifetime", 'N', 'N', 'N'),
    (10003_u32, "IsStealthed", 'N', 'N', 'N'),
    (10004_u32, "HasExpeditionInProgress", 'N', 'N', 'N'),
    (10005_u32, "IsExpeditionInProgress", 'R', 'N', 'N'),
    (10006_u32, "AbandonExpedition", 'N', 'N', 'N'),
    (10007_u32, "StartExpedition", 'R', 'N', 'N'),
    (10008_u32, "GetExpeditionsInstanceNumOptbjectivesCompleted", 'N', 'N', 'N'),
    (10009_u32, "ResetExpedition", 'R', 'N', 'N'),
    (10010_u32, "StartNewExpedition", 'R', 'N', 'N'),
    (10011_u32, "ResumeExpedition", 'R', 'N', 'N'),
    (10012_u32, "JoinExpedition", 'N', 'N', 'N'),
    (10013_u32, "GetPublicEventHasMutation", 'R', 'N', 'N'),
    (10014_u32, "IsUsingAltCurveTable", 'N', 'N', 'N'),
    (10015_u32, "GetIsInVATS", 'N', 'N', 'N'),
    (10016_u32, "GetIsDisguisedWithKeyword", 'R', 'N', 'N'),
    (10017_u32, "GetIsPlayerGhoul", 'N', 'N', 'N'),
    (10018_u32, "GetDistanceToClosestHostileActor", 'N', 'N', 'N'),
    (10019_u32, "GetRadshieldPercentage", 'N', 'N', 'N'),
    (10020_u32, "IsChallengeTypeMonthly", 'N', 'N', 'N'),
    (12000_u32, "IsFOWPersonalEWSEnabled", 'N', 'N', 'N'),
    (12001_u32, "GetWeakPointDamageMultiplier", 'N', 'N', 'N'),
    (12002_u32, "GetEquippedItemHealthPercent", 'R', 'N', 'N'),
    (12003_u32, "GetEquippedArmorHealthPercent", 'I', 'N', 'N'),
    (12004_u32, "GetEquippedWeaponHealthPercent", 'N', 'N', 'N'),
];

fn lookup(idx: u32) -> Option<(/* name */ &'static str, char, char, char)> {
    FUNCTIONS
        .binary_search_by_key(&idx, |e| e.0)
        .ok()
        .map(|i| {
            let e = &FUNCTIONS[i];
            (e.1, e.2, e.3, e.4)
        })
}

fn decode_param(bytes: &[u8; 4], class: char, ctx: &DecodeContext<'_>) -> Value {
    match class {
        'N' | 'S' => json!(null),
        'F' => json!(f32::from_le_bytes(*bytes)),
        'I' => json!(i32::from_le_bytes(*bytes)),
        'A' => json!(u32::from_le_bytes(*bytes)),
        'R' => {
            let id = FormId(u32::from_le_bytes(*bytes));
            resolve_formid(ctx, &[], id)
        }
        _ => json!(u32::from_le_bytes(*bytes)),
    }
}

/// Decode a 32-byte CTDA data block into a structured JSON object.
pub fn decode_ctda(data: &[u8], ctx: &DecodeContext<'_>) -> Value {
    if data.len() < 32 {
        return json!({"hex": hex::encode(data), "_raw": true});
    }

    let type_byte = data[0];
    // Bits 5-7: comparison operator.
    let op_idx = ((type_byte & 0xE0) >> 5) as usize;
    // Bit 0: AND vs OR with the previous condition.
    let is_or = (type_byte & 0x01) != 0;
    // Bit 2: comparison value is a Global FormID rather than a float.
    let use_global = (type_byte & 0x04) != 0;

    let operator = OPERATORS.get(op_idx).copied().unwrap_or("Unknown");

    // Bytes 4-7: comparison value.
    let comp_bytes: [u8; 4] = data[4..8].try_into().unwrap();
    let comp_value: Value = if use_global {
        resolve_formid(ctx, &[], FormId(u32::from_le_bytes(comp_bytes)))
    } else {
        json!(f32::from_le_bytes(comp_bytes))
    };

    // Bytes 8-9: function index.
    let func_idx = u16::from_le_bytes(data[8..10].try_into().unwrap()) as u32;

    // Bytes 12-15, 16-19, 28-31: parameters 1-3.
    let p1: [u8; 4] = data[12..16].try_into().unwrap();
    let p2: [u8; 4] = data[16..20].try_into().unwrap();
    let p3: [u8; 4] = data[28..32].try_into().unwrap();

    // Bytes 20-23: Run On target.
    let run_on_idx = u32::from_le_bytes(data[20..24].try_into().unwrap()) as usize;
    let run_on = RUN_ON.get(run_on_idx).copied().unwrap_or("Unknown");

    // Bytes 24-27: Reference (FormID, used when Run On = Reference).
    let ref_id = FormId(u32::from_le_bytes(data[24..28].try_into().unwrap()));

    let mut out = Map::new();
    out.insert("Operator".into(), json!(operator));
    out.insert("AND/OR".into(), json!(if is_or { "OR" } else { "AND" }));
    out.insert("Comparison Value".into(), comp_value);

    if let Some((name, c1, c2, c3)) = lookup(func_idx) {
        out.insert("Function".into(), json!(name));
        if c1 != 'N' {
            out.insert("Parameter 1".into(), decode_param(&p1, c1, ctx));
        }
        if c2 != 'N' {
            out.insert("Parameter 2".into(), decode_param(&p2, c2, ctx));
        }
        if c3 != 'N' {
            out.insert("Parameter 3".into(), decode_param(&p3, c3, ctx));
        }
    } else {
        out.insert("Function".into(), json!(func_idx));
        // Unknown function: emit all three params as raw hex.
        out.insert("Parameter 1".into(), json!({"hex": hex::encode(&p1)}));
        out.insert("Parameter 2".into(), json!({"hex": hex::encode(&p2)}));
        out.insert("Parameter 3".into(), json!({"hex": hex::encode(&p3)}));
    }

    out.insert("Run On".into(), json!(run_on));
    if ref_id.0 != 0 {
        out.insert("Reference".into(), resolve_formid(ctx, &[], ref_id));
    }

    Value::Object(out)
}

