/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class EsmDatabase {
  /**
   * Open an ESM file asynchronously (blocks on mmap + index build).
   *
   * Goes through a throwaway [`esm::registry::Registry`] rather than
   * calling `Database::open` directly — `Registry::get_or_open` first
   * canonicalizes `path` via `discover::resolve_esm_path` (folder→ESM
   * resolution plus `Path::canonicalize`), which `Database::open` alone
   * does not do (see `discover::resolve_esm_path`'s doc comment on why
   * every `esm_cache/` consumer must key off that same canonical path).
   * A fresh, unshared `Registry` per call preserves today's behavior —
   * one independent `Database` per `open_database` call, no cross-call
   * caching — while still fixing the canonicalization gap.
   */
  static openDatabase(path: string): Promise<EsmDatabase>
  fileInfo(): any
  listGroups(): any
  /** Paginated record rows for the given 4-character record type signature. */
  listTypeRecords(sig: string, offset: number, limit: number): any
  /**
   * Search records by EditorID and/or display name using a `*`-wildcard pattern.
   *
   * `types` restricts the search to the given 4-character record-type
   * signatures (empty = all types). `field` is one of `"edid"` | `"name"` |
   * `"both"`. `limit` caps the number of results (`0` = no limit).
   */
  search(pattern: string, types: Array<string>, field: string, limit: number): any
  /**
   * Filter records of type `sig` by a predicate against their decoded
   * field body. `path` is a dot-separated path (`"[]"` segments fan out
   * over arrays); `None`/empty deep-scans every field. `op` is one of
   * `"exists"` | `"eq"` | `"contains"` | `"gt"` | `"lt"` | `"gte"` | `"lte"`.
   * `limit` caps the number of returned rows (`0` = no limit).
   */
  filterTypeRecords(sig: string, path: string | undefined | null, op: string, value: string | undefined | null, limit: number): any
  /**
   * List every dot-notation field path observed across a (possibly capped)
   * decoded sample of a type's records — for filter-panel autocomplete.
   */
  listTypeFieldPaths(sig: string): any
  /** List direct children of the top-level GRUP with the given record type signature. */
  listTypeChildren(sig: string, offset: number, limit: number): any
  /**
   * List direct children of an arbitrary GRUP by its own header offset — used for
   * recursive descent below the top level (e.g. into a worldspace's exterior blocks,
   * then into a block's cells). `group_offset` is passed as `f64`/JS `number` rather
   * than a `u64`/BigInt: GRUP offsets fit exactly within f64's safe-integer range for
   * any realistic ESM file size, and this keeps the JS side free of BigInt handling.
   */
  listGroupChildren(groupOffset: number, offset: number, limit: number): any
  /**
   * Decode a record by FormID hex string (e.g. "0x0000463F").
   *
   * `resolve` controls FormID field expansion: `"none"` | `"stub"` | `"full"`.
   */
  recordByFormid(formid: string, resolve: string): any
  /**
   * Decode a record by EditorID string.
   *
   * `resolve` controls FormID field expansion: `"none"` | `"stub"` | `"full"`.
   */
  recordByEdid(edid: string, resolve: string): Promise<any>
  /**
   * Decode a record by FormID or EditorID (auto-detected).
   *
   * `resolve` controls FormID field expansion: `"none"` | `"stub"` | `"full"`.
   */
  recordById(id: string, resolve: string): Promise<any>
  /**
   * Return all records that reference the given FormID or EditorID (auto-detected).
   *
   * `depth` controls the reverse-reference walk depth (default 1 = direct refs only,
   * capped at DEFAULT_MAX_DEPTH = 8; pass 0 for an unbounded walk with no fixed hop
   * cap). Each returned row includes its hop `depth` and an intermediate-node `path`
   * array (empty for depth-1 results).
   */
  referencedById(id: string, depth?: number | undefined | null): Promise<any>
  /** Hex/subrecord dump of a record, by FormID or EditorID (auto-detected). */
  recordRaw(id: string): Promise<any>
  /**
   * Decode-coverage report: per-type counts of _unknown_record/_raw/_unmapped/
   * _unresolved markers. `record_type` (4-char sig, optional) restricts to one
   * type; `sample` caps records decoded per type (0 = unlimited).
   */
  coverageReport(recordType: string | undefined | null, sample: number): Promise<any>
  /**
   * Interactive digest of a record and the chain it references (see
   * `esm::walk`) — computed server-side (in-process here) via `Op::Walk`,
   * the same op the daemon and MCP server dispatch. `depth`/`ref_limit`/
   * `level` default to `esm::walk::DEFAULT_DEPTH`/
   * `esm::chase::DEFAULT_REF_LIMIT`/`esm::lvli::DEFAULT_LEVEL` when
   * omitted; `want_refs` mirrors the CLI's `--refs` flag.
   */
  walk(id: string, depth?: number | undefined | null, refLimit?: number | undefined | null, level?: number | undefined | null, wantRefs?: boolean | undefined | null): Promise<any>
  /**
   * Pipeline evidence contract: the classified mechanism tree for an
   * OMOD/PERK/SPEL/ALCH/ENCH selector (see `esm::chase`), computed
   * server-side via `Op::Chase`. `depth`/`ref_limit` default to
   * `esm::chase::DEFAULT_DEPTH`/`esm::chase::DEFAULT_REF_LIMIT` when
   * omitted.
   */
  chase(id: string, depth?: number | undefined | null, refLimit?: number | undefined | null): Promise<any>
  /**
   * Resolved LVLI drop-probability table (see `esm::lvli::drop_table`),
   * computed server-side via `Op::DropTable`. Hard errors on a non-LVLI
   * selector. `level` defaults to `esm::lvli::DEFAULT_LEVEL`;
   * `max_depth`/`strict` default to `esm::lvli::DropOptions::default()`'s
   * values.
   */
  lvliDropTable(id: string, level?: number | undefined | null): Promise<any>
  /**
   * Compare this database (treated as the "old"/base snapshot) against
   * `other` (the "new" snapshot). `record_type` (optional 4-char sig)
   * restricts the diff to one type; `bodies` is "none"|"stub"|"full"
   * (detail level for added/removed record bodies); `suppress_noise` strips
   * known-noisy fields (placement/CELL-precombine) from `changed` records;
   * `exclude_types` omits matching signatures from added/removed/changed
   * entirely.
   */
  diff(other: EsmDatabase, recordType: string | undefined | null, bodies: string, suppressNoise: boolean, excludeTypes: Array<string>): Promise<any>
}

/** Parse a FormID hex string to its display form. */
export declare function parseFormId(s: string): string
