/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Parse a FormID hex string to its display form. */
export declare function parseFormId(s: string): string
export declare class EsmDatabase {
  /** Open an ESM file asynchronously (blocks on mmap + index build). */
  static openDatabase(path: string): Promise<EsmDatabase>
  fileInfo(): any
  listGroups(): any
  /** Paginated record rows for the given 4-character record type signature. */
  listTypeRecords(sig: string, offset: number, limit: number): any
  /** List direct children of the top-level GRUP with the given record type signature. */
  listTypeChildren(sig: string, offset: number, limit: number): any
  /**
   * List direct children of an arbitrary GRUP by its own header offset — used for
   * recursive descent below the top level (e.g. into a worldspace's exterior blocks,
   * then into a block's cells). `group_offset` is passed as `f64`/JS `number` rather
   * than a `u64`/BigInt: GRUP offsets fit exactly within f64's safe-integer range for
   * any realistic ESM file size, and this keeps the JS side free of BigInt handling.
   */
  listGroupChildren(groupOffset: number, offset: number, limit: number): any
  /**
   * Decode a record by FormID hex string (e.g. "0x0000463F").
   *
   * `resolve` controls FormID field expansion: `"none"` | `"stub"` | `"full"`.
   */
  recordByFormid(formid: string, resolve: string): any
  /** Decode a record by EditorID string. */
  recordByEdid(edid: string): Promise<any>
  /**
   * Decode a record by FormID or EditorID (auto-detected).
   *
   * `resolve` controls FormID field expansion: `"none"` | `"stub"` | `"full"`.
   */
  recordById(id: string, resolve: string): Promise<any>
  /** Return all records that reference the given FormID hex string. */
  referencedBy(formid: string): Promise<any>
  /**
   * Return all records that reference the given FormID or EditorID (auto-detected).
   *
   * `depth` controls the reverse-reference walk depth (default 1 = direct refs only,
   * capped at DEFAULT_MAX_DEPTH = 6). Each returned row includes its hop `depth` and
   * an intermediate-node `path` array (empty for depth-1 results).
   */
  referencedById(id: string, depth?: number | undefined | null): Promise<any>
}
